pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

trigger: none

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    RunLiveTests: ${{ eq(variables['System.TeamProject'], 'internal') }}
